---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/commitizen-tools/commitizen
      rev: v2.42.0
      hooks:
          - id: commitizen
            stages: [commit-msg]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-ast
            stages: [commit]
          - id: end-of-file-fixer
            stages: [commit]
          - id: mixed-line-ending
            stages: [commit]
          - id: check-toml
            stages: [commit]
          - id: trailing-whitespace
            exclude: cm-cfg
            stages: [commit]
          - id: check-docstring-first
            stages: [commit]
          - id: check-yaml
            stages: [commit]
          - id: check-json
            stages: [commit]
          - id: pretty-format-json
            args: [--autofix, --indent=4]
            stages: [commit]
          - id: check-added-large-files
            stages: [commit]
          - id: requirements-txt-fixer
            stages: [commit]
          - id: check-merge-conflict
            stages: [commit]
          - id: debug-statements
            stages: [commit]
          - id: check-executables-have-shebangs
            language: python
            files: \.py$
            stages: [commit]
    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.4.2
      hooks:
          - id: remove-crlf
            stages: [commit]
          - id: remove-tabs
            exclude: cm-cfg
            stages: [commit]
          - id: forbid-crlf
            stages: [commit]
          - id: forbid-tabs
            exclude: cm-cfg
            stages: [commit]
    - repo: https://github.com/myint/eradicate
      rev: v2.1.0
      hooks:
          - id: eradicate
            name: eradicate
            description: Apply eradicate
            entry: eradicate
            language: python
            files: \.py$
            args: [--in-place]
            stages: [commit]
    - repo: https://github.com/timothycrosley/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: [--profile, black]
            name: isort
            entry: isort
            require_serial: true
            language: python
            types: [python]
            stages: [commit]
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.0.269
      hooks:
          - id: ruff
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.3.1
      hooks:
          - id: pyupgrade
            args: [--py39-plus, --keep-runtime-typing]
            stages: [commit]
    - repo: https://github.com/ikamensh/flynt/
      rev: '0.77'
      hooks:
          - id: flynt
            stages: [commit]
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.29.0
      hooks:
          - id: yamllint
            args: [--format, parsable]
            stages: [commit]
    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
          - id: black
            description: 'Black: The uncompromising Python code formatter'
            args: [--safe]
            stages: [commit]
    - repo: https://github.com/akaihola/darglint2
      rev: v1.8.2
      hooks:
          - id: darglint2
            args: [--docstring-style, sphinx]
    - repo: https://github.com/AleksaC/hadolint-py
      rev: v1.19.0
      hooks:
          - id: hadolint
            args: []
