# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

line-length = 88

target-version = "py311"


[lint]

ignore = [
    "ANN101", # annotation of self object
    "ANN204", # annotation of __init__()
    "D203",
    "D213",
    "FBT",    # boolean trap, no clear solution
    "N",      # naming convention, already covered by pylint
    "PT003",  # allow scope=function to be explicitly passed to fixtures
    "SIM114", # simplify if-elif by AND/OR combinations
    "TD",     # would conflict with TODO highligther
    "FIX002", # we need to keep TODOs in the code
    "E501",   # line too long ignoring
    "COM812", # The following rule may cause conflicts when used with the formatter
    "ISC001", # The following rule may cause conflicts when used with the formatter
    "S603",   # we allow this way of execution
    "S607",   # we allow it so that to support different platforms and environments
]

select = ["ALL"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]

unfixable = [
    "F401", # unused imports - we must know if we forgot something...
]

[lint.per-file-ignores]

"unittests/*" = [
    "INP001",  # pytest works this way
    "S101",    # we do use assert in unit test written for pytest
    "D103",    # doc-strings are not mandatory for unittests
    "SLF001",  # we do access private members for validation in unittests
    "E501",    # line too long errors are ignored for unittests
    "ANN401",  # dynamically typed expressions (typing.Any) are used in arguments
    "PLR2004", # Magic value used in comparison
]

[lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[format]
# Enable reformatting of code snippets in docstrings.
docstring-code-format = true
