---
version: '3.9'
services:
    router:
        container_name: router
        image: raikou/router
        build:
            context: https://github.com/lgirdk/raikou-net.git#main:components/router  # yamllint disable-line rule:line-length
            tags:
                - "router:frr_9.0"
        ports:
            - "4000:22"
        environment:
            DHCP_RELAY: "172.25.1.20,2001:dead:beef:2::20"
        privileged: true
        hostname: router
        depends_on:
            - ssh_service

    wan:
        container_name: wan
        image: raikou/wan
        build:
            context: https://github.com/lgirdk/raikou-net.git#main:components/wan  # yamllint disable-line rule:line-length
            tags:
                - "wan:lwds_lite_1.0"
        ports:
            - "4001:22"
        environment:
            DNS_UPSTREAM: "172.30.180.2"
            LEGACY: no  # yamllint disable-line rule:truthy
        privileged: true
        hostname: wan
        depends_on:
            - ssh_service

    lan:
        container_name: lan
        image: raikou/lan
        build:
            context: https://github.com/lgirdk/raikou-net.git#main:components/lan  # yamllint disable-line rule:line-length
            tags:
                - "lan:container_utils_1.1.1"
        ports:
            - "4002:22"
        environment:
            LEGACY: no  # yamllint disable-line rule:truthy
        privileged: true
        hostname: lan
        depends_on:
            - ssh_service

    dhcp:
        container_name: dhcp
        image: raikou/dhcp
        build:
            context: https://github.com/lgirdk/raikou-net.git#main:components/dhcp  # yamllint disable-line rule:line-length
            tags:
                - "dhcp:kea_dhcp_2.5.2"
        ports:
            - "4003:22"
        environment:
            LEGACY: no  # yamllint disable-line rule:truthy
        privileged: true
        hostname: dhcp
        depends_on:
            - ssh_service

    raikou-net:
        image: raikou/raikou-net
        build:
            context: https://github.com/lgirdk/raikou-net.git#main
            tags:
                - raikou-net:alpine3.18-dind-ovs_2.17
        volumes:
            - "/lib/modules:/lib/modules"
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "$NW_CONFIG:/root/config.json"
        privileged: true
        pid: host
        network_mode: host
        hostname: orchestrator
        depends_on:
            - router
            - wan
            - lan
            - dhcp

    ssh_service:
        image: raikou/ssh
        build:
            context: https://github.com/lgirdk/raikou-net.git#main:components/ssh  # yamllint disable-line rule:line-length
            tags:
                - "ssh:1.9.2p1"

networks:
    default:
        ipam:
            config:
                - subnet: 192.168.55.0/24
                  gateway: 192.168.55.1
